FROM golang:1.13-alpine AS builder

WORKDIR /app
COPY . .

RUN go get -d -v
RUN go build -ldflags '-w -s' -a -installsuffix cgo -o main main.go

## Multistage Building

FROM scratch

WORKDIR /app
COPY --from=builder /app .

CMD [ "/app/main" ]


