FROM golang:1.15.8-alpine3.13

WORKDIR /app
COPY . .

#RUN go build -o main main.go

RUN go get -d -v
#RUN go install -v
RUN go build -ldflags '-w -s' -a -installsuffix cgo -o main main.go

CMD [ "/app/main" ]
